---
language: python

sudo: required
dist: trusty

python:
  - '3.5'

node_js:
  - '8.12.0'

env:
  - DJANGO_CONFIGURATION: "Test"
  - DJANGO_TEST_WITH_WEB: "y"
  - DJANGO_TEST_WITH_ES: "y"

services:
  - redis-server
  - elasticsearch

# Run Django test sqlite db
# Prepare (install npm + pip dependencies, collect statics, locale)
install:
   - sudo apt-get update -qy
   - sudo apt-get install -y python-dev gettext pandoc
   - npm install
   - node_modules/.bin/webpack --config webpack.config.js
   - pip install -r requirements.txt
   - python manage.py collectstatic --no-input
   - python manage.py compilemessages --l de --l en

# Elasticsearch needs few seconds to start
before_script:
   - sleep 10

# Start tests
script:
   - coverage run --branch manage.py test
   - coverage report

# Generate test coverage
after_success:
  - coveralls
