---
language: python

sudo: required
dist: trusty

python:
  - '3.5'

env:
  - DJANGO_CONFIGURATION: "Test"

services:
  - redis-server

# Run Django test sqlite db
# Prepare (install dependencies, collect statics, locale)
install:
   - sudo apt-get update -qy
   - sudo apt-get install -y python-dev python-pip gettext pandoc
   - pip install -r requirements.txt
   - python manage.py collectstatic --no-input
   - python manage.py compilemessages --l de --l en

# Start tests
script:
   - python manage.py test

# Generate test coverage
after_success:
  - coveralls
