# Run using `docker-compose up`
version: "3"
services:
  app:
    image: openlegaldata/oldp:latest
    #build: .
    # container_name: oldp_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_CONFIGURATION=Dev
      - DJANGO_SECRET_KEY=change_this_value
      - DJANGO_REDIS_URL=redis://cache:6379/1
      - DJANGO_CACHE_DISABLE=1
      - DJANGO_ELASTICSEARCH_URL=http://search:9200/
      - DATABASE_URL=mysql://oldp:oldp@db/oldp
    volumes:
      - ./docker/data/static:/app/oldp/assets/static
      - ./docker/data/workingdir:/app/workingdir
      - ./docker/data/media:/app/media
      - ./docker/data/logs:/app/logs
    depends_on:
      - db
      - search
      - cache
    networks:
      - db_network
      - search_network
      - cache_network
  db:
    ports:
      # Make accessible by host machine
      - "3306:3306"
    # container_name: oldp_db
    image: mariadb
    volumes:
      # needs chmod 777
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=oldp
      - MYSQL_USER=oldp
      - MYSQL_PASSWORD=oldp
    networks:
      - db_network
  search:
    ports:
      # Make accessible by host machine
      - "9200:9200"
    # container_name: oldp_search
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - cluster.name=oldp
      - cluster.routing.allocation.disk.threshold_enabled=false
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    volumes:
      # chmod 777 the es_data directory so ES can write
      - ./docker/data/es:/usr/share/elasticsearch/data
    networks:
      - search_network
  cache:
    #container_name: oldp_cache
    ports:
      - "6379:6379"
    image: redis:4.0.5-alpine
    networks:
      - cache_network

networks:
  db_network:
    driver: bridge

  search_network:
    driver: bridge

  cache_network:
    driver: bridge
